my_frontend_album:
    resource: "@MyFrontendBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_album:
    resource: "@MyFrontendBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_album:
    resource: "@MyFrontendBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_album:
    resource: "@MyFrontendBundle/Controller/AlbumController.php"
    type:     annotation

my_frontend_image:
    resource: "@MyFrontendBundle/Controller/ImageController.php"
    type:     annotation

my_frontend_image:
    resource: "@MyFrontendBundle/Controller/ImageController.php"
    type:     annotation

my_frontend_tasks:
    resource: "@MyFrontendBundle/Controller/TasksController.php"
    type:     annotation

my_frontend_tasks:
    resource: "@MyFrontendBundle/Controller/TasksController.php"
    type:     annotation

my_user:
    resource: "@MyUserBundle/Controller/"
    type:     annotation
    prefix:   /user

my_frontend:
    resource: "@MyFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
